Data-services databag refactor
aodn/chef pull request #1041
Opened 2020-09-01 07:00 UTC by anguss00

2020-09-02 07:21 UTC, lwgordonimos commented
I feel like this has gone down a Ruby rabbit hole and away from Chef DSL, and there's a lot of broken abstractions as a result ;)

https://github.com/aodn/chef/pull/1042

Have a look here at adding the path at converge time. Basically, as soon as data-services is confirmed to exist, it adds the path, and any subsequent databag loading code will transparently use it.

The only thing to do do is then make talend a) formally depend on imos_po cookbook and b) update that loop to move that loop out of compile time, but it really needs to use a Chef resource model to avoid all the Ruby weirdness.

2020-09-02 07:30 UTC, anguss00 commented
@lwgordon OK no worries, that looks heaps cleaner

2020-09-02 07:30 UTC, lwgordonimos requested changes

2020-09-02 07:30 UTC, lwgordonimos commented on cookbooks/talend/recipes/default.rb
> +  bag_item = Talend::JobHelper.get_new_talend_job_config(job_name, node)
This is probably a useful refactor at the Ruby class level, but I wonder if we couldn't move the method call (and importantly the databag load) into the `talend_job` resource, to get it out of compile phase and into the converge phase?

2020-09-02 07:30 UTC, lwgordonimos commented on cookbooks/imos_po/libraries/pipeline_utils.rb
> +    def self.set_databag_path(node)
See my comment on the PR, I think this should be handled already by Chef, and not have databag stuff being leaked into these helper classes.

2020-09-03 00:34 UTC, anguss00 commented on cookbooks/talend/recipes/default.rb
> +  bag_item = Talend::JobHelper.get_new_talend_job_config(job_name, node)
Isn't this following the refactor of watch config though? That's what I based it off, refactoring the databag load into a library function rather than a resource. The resource stuff I found hard to reconcile as there's subsequent talend_job calls that use parts of the returned databag item

2020-09-03 00:43 UTC, anguss00 commented on cookbooks/talend/recipes/default.rb
> +  bag_item = Talend::JobHelper.get_new_talend_job_config(job_name, node)
ah sorry, just re-read the original comment - makes sense!

2020-09-03 00:45 UTC, lwgordonimos commented on cookbooks/talend/recipes/default.rb
> +  bag_item = Talend::JobHelper.get_new_talend_job_config(job_name, node)
The trouble is that this is just executing Ruby code in the recipe body still.

I can't see why you can't just supply `job_name` as a parameter to `talend_job` so that it can load the databag item when the resource executes? It seems like it's only ever giving the bag_item values to the resource anyway, so just let the resource load it.

2020-09-03 00:47 UTC, anguss00 commented on cookbooks/talend/recipes/default.rb
> +  bag_item = Talend::JobHelper.get_new_talend_job_config(job_name, node)
totally - yeah I understood above once I re-read hah

2020-09-03 00:49 UTC, lwgordonimos commented on cookbooks/talend/recipes/default.rb
> +  bag_item = Talend::JobHelper.get_new_talend_job_config(job_name, node)
Actually, it's already a parameter so it shouldn't be much more than refactoring this method call into the resource provider code:

https://github.com/aodn/chef/blob/master/cookbooks/talend/providers/job.rb#L29

2020-09-03 07:17 UTC, lwgordonimos requested changes

2020-09-03 07:17 UTC, lwgordonimos commented on cookbooks/imos_po/attributes/data_services.rb
> +default['imos_po']['data_services']['data_bag_dir'] =  ::File.join(node['imos_po']['data_services']['dir'], 'data_bags')
Can get rid of this now

2020-09-03 07:17 UTC, lwgordonimos commented on cookbooks/imos_po/libraries/pipeline_utils.rb
> -
This is unrelated code, so should leave this as is

2020-09-03 07:17 UTC, lwgordonimos commented on cookbooks/talend/providers/job.rb
> +  harvest_resources = job_config['resources']
Don't need to alias this, just use `job_config['resources']`

2020-09-03 07:17 UTC, lwgordonimos commented on cookbooks/talend/providers/job.rb
> +  trigger = job_config['trigger']
No need to alias this, just use `job_config['trigger']`

2020-09-03 07:17 UTC, lwgordonimos commented on cookbooks/talend/recipes/default.rb
> -    common_name job_id
Don't need to remove this

2020-09-07 02:30 UTC, lwgordonimos commented on cookbooks/talend/libraries/job_helper.rb
> +    def self.get_log_file_for_job(job_name, node)
Is this method used anywhere?

2020-09-07 02:30 UTC, lwgordonimos commented on private-sample/data_bags/imos_po_watches/ANMN_AM.json
> -{
I'd leave these databags in this PR, because this is just about the code feature, and this is really config changes (which should be considered separately).

2020-09-09 03:06 UTC, lwgordonimos commented on private-sample/data_bags/imos_po_watches/ANMN_AM.json
> -{
Sorry, being pedantic, but these still have whitespace changes in these databags which shouldn't be in the PR

2020-09-09 03:27 UTC, anguss00 commented on private-sample/data_bags/imos_po_watches/ANMN_AM.json
> -{
No sorry my bad - I copied from current master and something screwed up with the tab spaces

2020-09-09 06:23 UTC, lwgordonimos approved these changes

2020-09-09 07:00 UTC, merged